import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components";
import { SectionProvider } from "./Elements/Hooks/SectionContext";
import { IsMobileProvider } from "./Elements/Hooks/ScreenSizeContext";
import { PreventZoomProvider } from "./Elements/Hooks/PreventZoomContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ekko - Paisajismo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Img/logo/ekko-blanco.png" />
      </head>
      <PreventZoomProvider>
        <IsMobileProvider>
          <SectionProvider>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
              <Navbar />
              {children}
            </body>
          </SectionProvider>
        </IsMobileProvider>
      </PreventZoomProvider>
    </html>
  );
}
